item {
 id: 1
 name: 'Combustible'
}
item {
 id: 2
 name: 'DangerousWhenWet'
}
item {
 id: 3
 name: 'Explosive'
}
item {
 id: 4
 name: 'FlamableLiquid'
}
item {
 id: 5
 name: 'NonFlamableGas'
}
item {
 id: 6
 name: 'OrganicPeroxide'
}
item {
 id: 7
 name: 'Oxidizer'
}
item {
 id: 8
 name: 'RadioActive'
}
